version: "3.9"

services:
  php:
    build: .
    container_name: php-server
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres
    environment:
      PHP_ERRORS_STDERR: "1"

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: graduados_user
      POSTGRES_PASSWORD: graduados_pass
      POSTGRES_DB: graduados_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
